// The three plan cards of choose-plan.html, in page order.
// Feature `strong` is rendered bold, followed by `rest` as plain text.
export const PLANS = [
  {
    key: 'starter',
    price: 0,
    name: 'Starter Plan (Free)',
    popular: false,
    kicker: 'Free Forever',
    kickerColor: 'var(--blue)',
    title: 'Starter Plan',
    priceLabel: '₹0',
    description: 'Essential in-store POS billing and catalog for small retail shops and single counters.',
    features: [
      { strong: '2 Staff Accounts', rest: ' (Admin + Cashier)' },
      { strong: '1 Store Location' },
      { strong: 'Up to 300 Products' },
      { text: 'In-Store POS Scanning & Invoices' },
      { text: 'Daily Revenue & Sales Summary' },
      { text: 'Delivery Rider Dispatch', disabled: true },
      { text: 'Returns & Refund Management', disabled: true },
    ],
    buttonClass: 'btn btn-outline',
    buttonStyle: { width: '100%', justifyContent: 'center', padding: '11px', fontWeight: 600 },
    buttonLabel: 'Get Started Free',
  },
  {
    key: 'pro',
    price: 1999,
    name: 'Growth / Pro Plan',
    popular: true,
    kicker: 'Growth Tier',
    kickerColor: 'var(--accent)',
    title: 'Growth / Pro',
    priceLabel: '₹1,999',
    description: 'Omnichannel operations with delivery dispatches, returns handling, and promo engine.',
    features: [
      { strong: '10 Staff Accounts', rest: ' (Custom Roles)' },
      { strong: 'Up to 3 Store Locations' },
      { strong: 'Up to 5,000 Products' },
      { strong: 'Delivery Module', rest: ' & Live Dispatch' },
      { strong: 'Returns & Refund Engine' },
      { text: 'Discounts & Promo Campaigns' },
      { text: 'Advanced Trend & Stock Analytics' },
    ],
    buttonClass: 'btn btn-primary',
    buttonStyle: { width: '100%', justifyContent: 'center', padding: '11px', fontWeight: 700 },
    buttonLabel: 'Choose Growth / Pro',
  },
  {
    key: 'enterprise',
    price: 4999,
    name: 'Enterprise Plan',
    popular: false,
    kicker: 'Full Scale',
    kickerColor: 'var(--amber)',
    title: 'Enterprise Plan',
    priceLabel: '₹4,999',
    description: 'Multi-chain supermarkets, wholesale warehouses, and hypermarket networks.',
    features: [
      { strong: 'Unlimited Staff Accounts' },
      { strong: 'Unlimited Store Locations' },
      { strong: 'Unlimited Products & SKUs' },
      { text: 'Self-Checkout Kiosk Integration' },
      { text: 'Inter-Store Inventory Transfers' },
      { text: 'Dedicated 24/7 Phone SLA Support' },
    ],
    buttonClass: 'btn btn-outline',
    buttonStyle: { width: '100%', justifyContent: 'center', padding: '11px', fontWeight: 600, color: 'var(--amber)', borderColor: 'var(--amber)' },
    buttonLabel: 'Choose Enterprise',
  },
];
